name: Archlinux

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:

    container: archlinux:base-devel
    runs-on: ubuntu-latest

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Archlinux
        cancel-in-progress: true
    steps:
      - name: Prepare build tools
        run: |
          pacman -Syu --noconfirm --needed openssl
          pacman -Sy --noconfirm --needed glibc git base-devel perl make unzip
          pacman -Sy --noconfirm --needed mesa gcc-fortran glu
          git config --global --add safe.directory /__w/xmake/xmake

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: prepare local xmake
        run: |
          cp -rf . ../xmake-source
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: local#../xmake-source

      - name: Tests
        env:
          XMAKE_ROOT: y
        run: |
          xmake lua -v -D tests/run.lua
          xrepo --version

