name: Fedora

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:

    container: fedora:latest
    runs-on: ubuntu-latest

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Fedora
        cancel-in-progress: true
    steps:
      - name: Prepare build tools
        run: |
          uname -a
          dnf -y install @development-tools @rpm-development-tools
          dnf -y install mesa-libGL-devel mesa-libGLU-devel
          dnf -y install copr-cli make gcc-c++
          dnf -y install perl
          dnf -y upgrade git
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Prepare local xmake
        run: |
          cp -rf . ../xmake-source
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: local#../xmake-source

      - name: Tests
        env:
          XMAKE_ROOT: y
        run: |
          xmake lua -v -D tests/run.lua
          xrepo --version

